export const UI_ELEMENTS = {
	SWITCH_TABS: document.querySelectorAll('.tab-item'),
	CONTENT_TABS: document.querySelectorAll('.content'),
	FORM: document.querySelector('.form'),
	LIKE_BTN: document.querySelector('.like_btn'),
	FAVORITE_CITIES: document.querySelector('.main__favorite-bottom'),
	FORECAST_LIST: document.querySelector('.forecast-list'),
	SET_CITY: document.querySelectorAll('.city'),
	SET_DEGREE: document.querySelectorAll('.degree'),
	SET_WEATHER_ICON: document.querySelector('.picture'),
	SET_FEEL_LIKE: document.querySelector('.feel-like'),
	SET_WEATHER: document.querySelector('.weather-detailed'),
	SET_SUNRISE: document.querySelector('.sunrise'),
	SET_SUNSET: document.querySelector('.sunset'),
}
